title: "B1m3rU"
description: "Proyectos, notas y avances."
theme: jekyll-theme-hacker
# theme: minima

author: "Enrique Álvarez González"

# Páginas que aparecerán en el menú superior
header_pages:
  - about.md
  - maquinas.md
  - contact.md

# Opcional: esquema de colores del tema minima
# minima:
#   skin: dark
#   social_links:
#     - { platform: github,  user_url: "https://github.com/B1m3rU" }
#     - { platform: linkedin, user_url: "https://www.linkedin.com/in/tu-perfil/" }


# Opcional: configuración básica de enlaces y cosas del sitio
url: "https://b1m3ru.github.io/"

# Forzar a que Jekyll use nuestra hoja de estilos personalizada
sass:
  sass_dir: assets
